In [1]:
# Pybank data. Converting the csv file into Pandas dataframe and then to numpy array
import numpy as np
import pandas as pd

# Fetching the CSV file from the directory
df= pd.read_csv(r'C:\Satheesh\My Folder\Quant\UC Berkeley\Classwork\ucb-sfc-fin-pt-08-2020-u-c\02-Homework\02-Python\Instructions\PyBank\Resources\budget_data.csv')

# Printing the Pandas dataframe
print (df)

        Date  Profit/Losses
0   Jan-2010         867884
1   Feb-2010         984655
2   Mar-2010         322013
3   Apr-2010         -69417
4   May-2010         310503
..       ...            ...
81  Oct-2016         102685
82  Nov-2016         795914
83  Dec-2016          60988
84  Jan-2017         138230
85  Feb-2017         671099

[86 rows x 2 columns]

In [2]:
# Converting the Pandas dataframe to numpy array
sales_record= df.to_numpy()
display (sales_record)

array([['Jan-2010', 867884],
       ['Feb-2010', 984655],
       ['Mar-2010', 322013],
       ['Apr-2010', -69417],
       ['May-2010', 310503],
       ['Jun-2010', 522857],
       ['Jul-2010', 1033096],
       ['Aug-2010', 604885],
       ['Sep-2010', -216386],
       ['Oct-2010', 477532],
       ['Nov-2010', 893810],
       ['Dec-2010', -80353],
       ['Jan-2011', 779806],
       ['Feb-2011', -335203],
       ['Mar-2011', 697845],
       ['Apr-2011', 793163],
       ['May-2011', 485070],
       ['Jun-2011', 584122],
       ['Jul-2011', 62729],
       ['Aug-2011', 668179],
       ['Sep-2011', 899906],
       ['Oct-2011', 834719],
       ['Nov-2011', 132003],
       ['Dec-2011', 309978],
       ['Jan-2012', -755566],
       ['Feb-2012', 1170593],
       ['Mar-2012', 252788],
       ['Apr-2012', 1151518],
       ['May-2012', 817256],
       ['Jun-2012', 570757],
       ['Jul-2012', 506702],
       ['Aug-2012', -1022534],
       ['Sep-2012', 475062],
       ['Oct-2012', 779976],
       ['Nov-2012', 144175],
       ['Dec-2012', 542494],
       ['Jan-2013', 359333],
       ['Feb-2013', 321469],
       ['Mar-2013', 67780],
       ['Apr-2013', 471435],
       ['May-2013', 565603],
       ['Jun-2013', 872480],
       ['Jul-2013', 789480],
       ['Aug-2013', 999942],
       ['Sep-2013', -1196225],
       ['Oct-2013', 268997],
       ['Nov-2013', -687986],
       ['Dec-2013', 1150461],
       ['Jan-2014', 682458],
       ['Feb-2014', 617856],
       ['Mar-2014', 824098],
       ['Apr-2014', 581943],
       ['May-2014', 132864],
       ['Jun-2014', 448062],
       ['Jul-2014', 689161],
       ['Aug-2014', 800701],
       ['Sep-2014', 1166643],
       ['Oct-2014', 947333],
       ['Nov-2014', 578668],
       ['Dec-2014', 988505],
       ['Jan-2015', 1139715],
       ['Feb-2015', 1029471],
       ['Mar-2015', 687533],
       ['Apr-2015', -524626],
       ['May-2015', 158620],
       ['Jun-2015', 87795],
       ['Jul-2015', 423389],
       ['Aug-2015', 840723],
       ['Sep-2015', 568529],
       ['Oct-2015', 332067],
       ['Nov-2015', 989499],
       ['Dec-2015', 778237],
       ['Jan-2016', 650000],
       ['Feb-2016', -1100387],
       ['Mar-2016', -174946],
       ['Apr-2016', 757143],
       ['May-2016', 445709],
       ['Jun-2016', 712961],
       ['Jul-2016', -1163797],
       ['Aug-2016', 569899],
       ['Sep-2016', 768450],
       ['Oct-2016', 102685],
       ['Nov-2016', 795914],
       ['Dec-2016', 60988],
       ['Jan-2017', 138230],
       ['Feb-2017', 671099]], dtype=object)

In [83]:
# Initializing metric variables
total_revenue= 0
total_months= 0
average= 0
difference= 0

#Initializing max increase key-value pair
max_increase= 0
max_increase_month= ""

#Initializing max decrease key-value pair
max_decrease= 0
max_decrease_month= ""

# Initializing profitable/unprofitable months
profitable_months= {}
unprofitable_months= {}

# Iterating over key-value pair
for month, revenue in sales_record:
               
    # Sum of months and revenue
    total_revenue += int (revenue)
    total_months += 1

  
    difference += int[(revenue[n+1])- int(revenue[n])]
    
    profitable_months.append(month,revenue)
   
    unprofitable_months.append(month,revenue)


# Creating a for-loop to iterate over profitable months list
for months1, revenues1 in profitable_months:
    max_increase += max(revenues1) 
    
    # Logic to determine the respective month, max increase pair
    if max_increase == 0:
        max_increase= revenues1
        max_increase_month= month1
    elif revenues1> max_increase:
        max_increase= revenues1
        max_increase_month= month1

# Creating a for-loop to iterate over unprofitable months list
for months2, revenues2 in unprofitable_months:
    max_decrease += min(revenues2)
    
    # Logic to determine the respective month, max decrease pair
    if revenues2> max_decrease:
        max_decrease= revenues2
        
# Calculate the total number of months
print(f"Total Months: {total_months}")

# Profit/Loss over the entire period
print(f"Total Revenue: {total_revenue}")

# Average change in profit/loss
average_change_in_profit_loss= round (sum(difference)/{total_months}, 2)
print(f"Average change: {average_change_in_profit_loss}")
        
# Printing greatest increase in profit
print(f"Greatest increase in profit: {max_increase}")

# Printing greatest decrease in profit
print(f"Greatest decrease in profit: {max_decrease}")

SyntaxError: invalid syntax (<ipython-input-83-4f30fa23a913>, line 29)